name: hotel_time
description: Hotel Time application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5  
  json_annotation: ^4.8.0
  hive_flutter: ^1.1.0
  auto_route: ^7.8.0  
  flutter_linkify: ^6.0.0
  url_launcher: ^6.0.17
  provider: ^6.0.5
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:  
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  auto_route_generator: ^7.3.1

flutter:
  uses-material-design: true
  generate: false

  assets:
  - assets/images/

flutter_intl:
  enabled: true